version: "3.8"

#Docker Networks
networks:
  csproject:
    driver: bridge
    external: true

#Volumes
volumes:
  dbdata:
    driver: local
  api_gateway-api-data:
    name: api_gateway-api-data
  redis:
    driver: local

  # Workflow
services:
  api_gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api_gateway
    ports:
      - 8085:80
    volumes:
      - api_gateway-api-data:/var/www/html
    networks:
      - csproject
  api_gateway_cache:
    image: redis
    container_name: api_gateway_cache
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - csproject
    volumes:
      - redis:/data