version: "3.8"

#Docker Networks
networks:
  csproject:
    driver: bridge
    external: true

#Volumes
volumes:
  dbdata:
    driver: local
  api_gateway-api-data:
    name: api_gateway-api-data

  # Workflow
services:
  api_gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api_gateway
    ports:
      - 8085:80
    volumes:
      - .:/var/www/html
    networks:
      - csproject